### ISSUE TITLE
Project seed is currently broken

### ISSUE THREAD

**Issue by sirtawast** [ultimatecourses/rxjs-basics#1]
Hi @btroncone and @toddmotto. Just started your RxJS course and the material gave me a bit of trouble.

Related: https://github.com/parcel-bundler/parcel/issues/5943

I got through `npm start` by removing `node_modules` and `package-lock.json` and then using modified `package.json` as follows:

Modify:

```
  "dependencies": {
    "parcel-bundler": "1.12.3",
    "rxjs": "^6.5.3"
  },
```

Add:

```
  "resolutions": {
    "@babel/preset-env": "7.13.8"
  },
```

Now `npm install` and `npm start` and it works again.

**Comment by sirtawast** [comment]
The actual error:


`$ npm start`

```
> rxjs-starter@1.0.0 start /path/to/rxjs-basics-master
> parcel index.html

Server running at http://localhost:1234
🚨  /path/to/rxjs-basics-master/index.js: Invalid Version: undefined
    at new SemVer (/path/to/rxjs-basics-master/node_modules/@babel/preset-env/node_modules/semver/semver.js:314:11)
    at compare (/path/to/rxjs-basics-master/node_modules/@babel/preset-env/node_modules/semver/semver.js:647:10)
    at lt (/path/to/rxjs-basics-master/node_modules/@babel/preset-env/node_modules/semver/semver.js:688:10)
    at /path/to/rxjs-basics-master/node_modules/@babel/preset-env/lib/index.js:280:22
    at Object.default (/path/to/rxjs-basics-master/node_modules/@babel/helper-plugin-utils/lib/index.js:22:12)
    at getEnvPlugins (/path/to/rxjs-basics-master/node_modules/parcel-bundler/src/transforms/babel/env.js:62:34)
    at getEnvConfig (/path/to/rxjs-basics-master/node_modules/parcel-bundler/src/transforms/babel/env.js:12:25)
    at async getBabelConfig (/path/to/rxjs-basics-master/node_modules/parcel-bundler/src/transforms/babel/config.js:32:19)
    at async babelTransform (/path/to/rxjs-basics-master/node_modules/parcel-bundler/src/transforms/babel/transform.js:6:16)
    at async JSAsset.pretransform (/path/to/rxjs-basics-master/node_modules/parcel-bundler/src/assets/JSAsset.js:83:5)
```

**Comment by AdamMescher** [comment]
As of 6/3/2021, I was able to successfully run the commands listed in the setup instructions
- `npm install`
- `npm start`

Node Version: `v12.18.1`
NPM Version: `7.13.0`
OS: Ubuntu 20.04.2 LTS on Windows 10 x86_64
Kernel: 4.19.128-microsoft-standard
